# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Users/debrajray/MyComputer/anaconda/anaconda3/bin/cmake

# The command to remove a file.
RM = /Users/debrajray/MyComputer/anaconda/anaconda3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/debrajray/MyComputer/RTS/hog2_debraj/hog2/apps/game1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/debrajray/MyComputer/RTS/hog2_debraj/hog2/apps/game1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Users/debrajray/MyComputer/anaconda/anaconda3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Users/debrajray/MyComputer/anaconda/anaconda3/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/debrajray/MyComputer/RTS/hog2_debraj/hog2/apps/game1/CMakeFiles /Users/debrajray/MyComputer/RTS/hog2_debraj/hog2/apps/game1//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/debrajray/MyComputer/RTS/hog2_debraj/hog2/apps/game1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named example

# Build rule for target.
example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example
.PHONY : example

# fast build rule for target.
example/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/build
.PHONY : example/fast

AStarOpenList.o: AStarOpenList.cpp.o

.PHONY : AStarOpenList.o

# target to build an object file
AStarOpenList.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/AStarOpenList.cpp.o
.PHONY : AStarOpenList.cpp.o

AStarOpenList.i: AStarOpenList.cpp.i

.PHONY : AStarOpenList.i

# target to preprocess a source file
AStarOpenList.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/AStarOpenList.cpp.i
.PHONY : AStarOpenList.cpp.i

AStarOpenList.s: AStarOpenList.cpp.s

.PHONY : AStarOpenList.s

# target to generate assembly for a file
AStarOpenList.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/AStarOpenList.cpp.s
.PHONY : AStarOpenList.cpp.s

AStar_.o: AStar_.cpp.o

.PHONY : AStar_.o

# target to build an object file
AStar_.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/AStar_.cpp.o
.PHONY : AStar_.cpp.o

AStar_.i: AStar_.cpp.i

.PHONY : AStar_.i

# target to preprocess a source file
AStar_.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/AStar_.cpp.i
.PHONY : AStar_.cpp.i

AStar_.s: AStar_.cpp.s

.PHONY : AStar_.s

# target to generate assembly for a file
AStar_.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/AStar_.cpp.s
.PHONY : AStar_.cpp.s

coordinatesUtil.o: coordinatesUtil.cpp.o

.PHONY : coordinatesUtil.o

# target to build an object file
coordinatesUtil.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/coordinatesUtil.cpp.o
.PHONY : coordinatesUtil.cpp.o

coordinatesUtil.i: coordinatesUtil.cpp.i

.PHONY : coordinatesUtil.i

# target to preprocess a source file
coordinatesUtil.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/coordinatesUtil.cpp.i
.PHONY : coordinatesUtil.cpp.i

coordinatesUtil.s: coordinatesUtil.cpp.s

.PHONY : coordinatesUtil.s

# target to generate assembly for a file
coordinatesUtil.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/coordinatesUtil.cpp.s
.PHONY : coordinatesUtil.cpp.s

enemy/fixedEnemy.o: enemy/fixedEnemy.cpp.o

.PHONY : enemy/fixedEnemy.o

# target to build an object file
enemy/fixedEnemy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/enemy/fixedEnemy.cpp.o
.PHONY : enemy/fixedEnemy.cpp.o

enemy/fixedEnemy.i: enemy/fixedEnemy.cpp.i

.PHONY : enemy/fixedEnemy.i

# target to preprocess a source file
enemy/fixedEnemy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/enemy/fixedEnemy.cpp.i
.PHONY : enemy/fixedEnemy.cpp.i

enemy/fixedEnemy.s: enemy/fixedEnemy.cpp.s

.PHONY : enemy/fixedEnemy.s

# target to generate assembly for a file
enemy/fixedEnemy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/enemy/fixedEnemy.cpp.s
.PHONY : enemy/fixedEnemy.cpp.s

enemyLocator.o: enemyLocator.cpp.o

.PHONY : enemyLocator.o

# target to build an object file
enemyLocator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/enemyLocator.cpp.o
.PHONY : enemyLocator.cpp.o

enemyLocator.i: enemyLocator.cpp.i

.PHONY : enemyLocator.i

# target to preprocess a source file
enemyLocator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/enemyLocator.cpp.i
.PHONY : enemyLocator.cpp.i

enemyLocator.s: enemyLocator.cpp.s

.PHONY : enemyLocator.s

# target to generate assembly for a file
enemyLocator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/enemyLocator.cpp.s
.PHONY : enemyLocator.cpp.s

example.o: example.cpp.o

.PHONY : example.o

# target to build an object file
example.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/example.cpp.o
.PHONY : example.cpp.o

example.i: example.cpp.i

.PHONY : example.i

# target to preprocess a source file
example.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/example.cpp.i
.PHONY : example.cpp.i

example.s: example.cpp.s

.PHONY : example.s

# target to generate assembly for a file
example.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/example.cpp.s
.PHONY : example.cpp.s

findPath.o: findPath.cpp.o

.PHONY : findPath.o

# target to build an object file
findPath.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/findPath.cpp.o
.PHONY : findPath.cpp.o

findPath.i: findPath.cpp.i

.PHONY : findPath.i

# target to preprocess a source file
findPath.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/findPath.cpp.i
.PHONY : findPath.cpp.i

findPath.s: findPath.cpp.s

.PHONY : findPath.s

# target to generate assembly for a file
findPath.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/findPath.cpp.s
.PHONY : findPath.cpp.s

fixedobstacles.o: fixedobstacles.cpp.o

.PHONY : fixedobstacles.o

# target to build an object file
fixedobstacles.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/fixedobstacles.cpp.o
.PHONY : fixedobstacles.cpp.o

fixedobstacles.i: fixedobstacles.cpp.i

.PHONY : fixedobstacles.i

# target to preprocess a source file
fixedobstacles.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/fixedobstacles.cpp.i
.PHONY : fixedobstacles.cpp.i

fixedobstacles.s: fixedobstacles.cpp.s

.PHONY : fixedobstacles.s

# target to generate assembly for a file
fixedobstacles.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/fixedobstacles.cpp.s
.PHONY : fixedobstacles.cpp.s

gameEnv.o: gameEnv.cpp.o

.PHONY : gameEnv.o

# target to build an object file
gameEnv.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/gameEnv.cpp.o
.PHONY : gameEnv.cpp.o

gameEnv.i: gameEnv.cpp.i

.PHONY : gameEnv.i

# target to preprocess a source file
gameEnv.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/gameEnv.cpp.i
.PHONY : gameEnv.cpp.i

gameEnv.s: gameEnv.cpp.s

.PHONY : gameEnv.s

# target to generate assembly for a file
gameEnv.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/gameEnv.cpp.s
.PHONY : gameEnv.cpp.s

gameSimulation.o: gameSimulation.cpp.o

.PHONY : gameSimulation.o

# target to build an object file
gameSimulation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/gameSimulation.cpp.o
.PHONY : gameSimulation.cpp.o

gameSimulation.i: gameSimulation.cpp.i

.PHONY : gameSimulation.i

# target to preprocess a source file
gameSimulation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/gameSimulation.cpp.i
.PHONY : gameSimulation.cpp.i

gameSimulation.s: gameSimulation.cpp.s

.PHONY : gameSimulation.s

# target to generate assembly for a file
gameSimulation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/gameSimulation.cpp.s
.PHONY : gameSimulation.cpp.s

node_.o: node_.cpp.o

.PHONY : node_.o

# target to build an object file
node_.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/node_.cpp.o
.PHONY : node_.cpp.o

node_.i: node_.cpp.i

.PHONY : node_.i

# target to preprocess a source file
node_.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/node_.cpp.i
.PHONY : node_.cpp.i

node_.s: node_.cpp.s

.PHONY : node_.s

# target to generate assembly for a file
node_.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/node_.cpp.s
.PHONY : node_.cpp.s

observation.o: observation.cpp.o

.PHONY : observation.o

# target to build an object file
observation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/observation.cpp.o
.PHONY : observation.cpp.o

observation.i: observation.cpp.i

.PHONY : observation.i

# target to preprocess a source file
observation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/observation.cpp.i
.PHONY : observation.cpp.i

observation.s: observation.cpp.s

.PHONY : observation.s

# target to generate assembly for a file
observation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/observation.cpp.s
.PHONY : observation.cpp.s

player.o: player.cpp.o

.PHONY : player.o

# target to build an object file
player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/player.cpp.o
.PHONY : player.cpp.o

player.i: player.cpp.i

.PHONY : player.i

# target to preprocess a source file
player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/player.cpp.i
.PHONY : player.cpp.i

player.s: player.cpp.s

.PHONY : player.s

# target to generate assembly for a file
player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/player.cpp.s
.PHONY : player.cpp.s

plot/pbPlots.o: plot/pbPlots.cpp.o

.PHONY : plot/pbPlots.o

# target to build an object file
plot/pbPlots.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/plot/pbPlots.cpp.o
.PHONY : plot/pbPlots.cpp.o

plot/pbPlots.i: plot/pbPlots.cpp.i

.PHONY : plot/pbPlots.i

# target to preprocess a source file
plot/pbPlots.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/plot/pbPlots.cpp.i
.PHONY : plot/pbPlots.cpp.i

plot/pbPlots.s: plot/pbPlots.cpp.s

.PHONY : plot/pbPlots.s

# target to generate assembly for a file
plot/pbPlots.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/plot/pbPlots.cpp.s
.PHONY : plot/pbPlots.cpp.s

plot/supportLib.o: plot/supportLib.cpp.o

.PHONY : plot/supportLib.o

# target to build an object file
plot/supportLib.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/plot/supportLib.cpp.o
.PHONY : plot/supportLib.cpp.o

plot/supportLib.i: plot/supportLib.cpp.i

.PHONY : plot/supportLib.i

# target to preprocess a source file
plot/supportLib.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/plot/supportLib.cpp.i
.PHONY : plot/supportLib.cpp.i

plot/supportLib.s: plot/supportLib.cpp.s

.PHONY : plot/supportLib.s

# target to generate assembly for a file
plot/supportLib.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/plot/supportLib.cpp.s
.PHONY : plot/supportLib.cpp.s

rl_control.o: rl_control.cpp.o

.PHONY : rl_control.o

# target to build an object file
rl_control.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/rl_control.cpp.o
.PHONY : rl_control.cpp.o

rl_control.i: rl_control.cpp.i

.PHONY : rl_control.i

# target to preprocess a source file
rl_control.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/rl_control.cpp.i
.PHONY : rl_control.cpp.i

rl_control.s: rl_control.cpp.s

.PHONY : rl_control.s

# target to generate assembly for a file
rl_control.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/rl_control.cpp.s
.PHONY : rl_control.cpp.s

state.o: state.cpp.o

.PHONY : state.o

# target to build an object file
state.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/state.cpp.o
.PHONY : state.cpp.o

state.i: state.cpp.i

.PHONY : state.i

# target to preprocess a source file
state.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/state.cpp.i
.PHONY : state.cpp.i

state.s: state.cpp.s

.PHONY : state.s

# target to generate assembly for a file
state.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/state.cpp.s
.PHONY : state.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... example"
	@echo "... AStarOpenList.o"
	@echo "... AStarOpenList.i"
	@echo "... AStarOpenList.s"
	@echo "... AStar_.o"
	@echo "... AStar_.i"
	@echo "... AStar_.s"
	@echo "... coordinatesUtil.o"
	@echo "... coordinatesUtil.i"
	@echo "... coordinatesUtil.s"
	@echo "... enemy/fixedEnemy.o"
	@echo "... enemy/fixedEnemy.i"
	@echo "... enemy/fixedEnemy.s"
	@echo "... enemyLocator.o"
	@echo "... enemyLocator.i"
	@echo "... enemyLocator.s"
	@echo "... example.o"
	@echo "... example.i"
	@echo "... example.s"
	@echo "... findPath.o"
	@echo "... findPath.i"
	@echo "... findPath.s"
	@echo "... fixedobstacles.o"
	@echo "... fixedobstacles.i"
	@echo "... fixedobstacles.s"
	@echo "... gameEnv.o"
	@echo "... gameEnv.i"
	@echo "... gameEnv.s"
	@echo "... gameSimulation.o"
	@echo "... gameSimulation.i"
	@echo "... gameSimulation.s"
	@echo "... node_.o"
	@echo "... node_.i"
	@echo "... node_.s"
	@echo "... observation.o"
	@echo "... observation.i"
	@echo "... observation.s"
	@echo "... player.o"
	@echo "... player.i"
	@echo "... player.s"
	@echo "... plot/pbPlots.o"
	@echo "... plot/pbPlots.i"
	@echo "... plot/pbPlots.s"
	@echo "... plot/supportLib.o"
	@echo "... plot/supportLib.i"
	@echo "... plot/supportLib.s"
	@echo "... rl_control.o"
	@echo "... rl_control.i"
	@echo "... rl_control.s"
	@echo "... state.o"
	@echo "... state.i"
	@echo "... state.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

